# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Show all available tasks 
    cmds:
      - task --list-all
    silent: true
    
  greet:
    desc: Greet the specified person.
    cmds:
      - echo "{{.GREETING}}"
    silent: true
